In [2]:
!pip install mp-api --upgrade
import numpy as np
from mp_api.client import MPRester
#from pymatgen.ext.matproj import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python3.9 -m pip install --upgrade pip


In [3]:
mp_key = "MgnCbwKILRoKeWCsa2tbfn04aBTHkB78"
mp_id = "mp-1747"

In [4]:
with MPRester(mp_key) as m:
    print("Téléchargement du fichier CIF de K2Te..")
    prim_struc = m.get_structure_by_material_id(mp_id)
    print("Téléchargement terminé")
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()

Téléchargement du fichier CIF de K2Te..


Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Téléchargement terminé


In [5]:
a=prim_struc.lattice.a
alpha=prim_struc.lattice.alpha
print("Vecteurs de base du réseau direct :")
print(SpacegroupAnalyzer(prim_struc).find_primitive().lattice.rhombohedral(a,alpha).matrix)
print("\n")

Vecteurs de base du réseau direct :
[[5.01066174 0.         2.89290605]
 [1.67022033 4.72409728 2.89290605]
 [0.         0.         5.78581338]]




In [6]:

a=conv_struc.lattice.a
print("Vecteurs de base du réseau réciproque :")
print(SpacegroupAnalyzer(conv_struc).find_primitive().lattice.cubic(a).matrix)
print("\n")

Vecteurs de base du réseau réciproque :
[[8.18237593 0.         0.        ]
 [0.         8.18237593 0.        ]
 [0.         0.         8.18237593]]




In [7]:
spa = SpacegroupAnalyzer(prim_struc,0.1)
#type de maille
maille = spa.get_lattice_type()
#système cristallin
sys = spa.get_crystal_system()
#groupe ponctuel
ponc = spa.get_point_group_symbol()

print("Type de maille de K2Te :", maille)
print("Système cristallin :",sys)
print("Groupe ponctuel :" ,ponc)

Type de maille de K2Te : cubic
Système cristallin : cubic
Groupe ponctuel : m-3m
