In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
mp_key = "MgnCbwKILRoKeWCsa2tbfn04aBTHkB78"
mp_id = "mp-1747"

In [3]:
with MPRester(mp_key) as m:
    print("Téléchargement du fichier CIF de K2Te..")
    prim_struc = m.get_structure_by_material_id(mp_id)
    print("Téléchargement terminé")
symmops = SpacegroupAnalyzer(prim_struc).get_symmetry_operations()
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()

Téléchargement du fichier CIF de K2Te..


Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Téléchargement terminé


 ## Choix des atomes et des symétries

In [14]:
#Choix des atomes:
pos_init_Te = conv_struc.sites[10].frac_coords
pos_init_K1 = conv_struc.sites[7].frac_coords
pos_init_K2 = conv_struc.sites[1].frac_coords

#Plan miroir xy (x, z, y)
s1 = symmops[31]
Te_symmetry = s1.operate(pos_init_Te)

#Roto-inversion (-x,-z,-y)
s2 = symmops [28]
K1_symmetry = s2.operate(pos_init_K1)

#Rotation axe d'ordre 2 (y, x, -x-y-z)
s3 = symmops [14]
K2_symmetry = s3.operate(pos_init_K2)

print("Les atomes étudiés sont : Te situé en {0}, K1 situé en {1} et K2 situé en {2}. \n symétries étudiées sont : un plan miroir xy sur Te, une roto-inversion (-x, -y, -z) \n K1 et une rotation autour d'un axe d'ordre 2 (y, x, -x-y-z) pour K2".format(pos_init_Te, pos_init_K1, pos_init_K2))

Les atomes étudiés sont : Te situé en [0.5 0.  0.5], K1 situé en [0.25 0.25 0.25] et K2 situé en [0.75 0.75 0.25]. 
 symétries étudiées sont : un plan miroir xy sur Te, une roto-inversion (-x, -y, -z) 
 K1 et une rotation autour d'un axe d'ordre 2 (y, x, -x-y-z) pour K2


In [15]:
## Symétrie 1 : Plan miroir xy 

In [16]:
print("  Nous pouvons voir dans la figure ci dessous que l'atome de Tellure initialement \n situé aux coordonnées : {0} subit une symétrie (x, z, y) avec un plan miroit xy pour \n arriver à la position {1}. \n L'opération de symétrie est donnée par la matrice de rotation : \n {2} \n et le vecteur de translation {3} ".format(pos_init_Te, Te_symmetry, s1.rotation_matrix, s1.translation_vector))
v1 = quick_view(conv_struc, conventional = "True")
display(v1)
v1.script("draw SYMOP 32 {atomno=19}")
v1.script("rotate on")


  Nous pouvons voir dans la figure ci dessous que l'atome de Tellure initialement 
 situé aux coordonnées : [0.5 0.  0.5] subit une symétrie (x, z, y) avec un plan miroit xy pour 
 arriver à la position [0.5 0.5 0. ]. 
 L'opération de symétrie est donnée par la matrice de rotation : 
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]] 
 et le vecteur de translation [0. 0. 0.] 


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [17]:
## Symétrie 2 : Roto-inversion (-x, -z, -y)

In [18]:
print("  Nous pouvons voir dans la figure ci dessous que l'atome de Potassium n°1 initialement \n situé aux coordonnées : {0} subit une symétrie de plan miroir pour \n arriver à la position {1}. \n L'opération de symétrie est donnée par la matrice de rotation : \n {2} \n et le vecteur de translation {3} ".format(pos_init_K1, K2_symmetry, s2.rotation_matrix, s2.translation_vector))
v2 = quick_view(conv_struc, conventional = "True")
display(v2)
v2.script("draw SYMOP 29 {atomno=1}")
v2.script("rotate on")

  Nous pouvons voir dans la figure ci dessous que l'atome de Potassium n°1 initialement 
 situé aux coordonnées : [0.25 0.25 0.25] subit une symétrie de plan miroir pour 
 arriver à la position [ 0.25  0.75 -1.75]. 
 L'opération de symétrie est donnée par la matrice de rotation : 
 [[-1.  0.  0.]
 [ 0.  0. -1.]
 [ 0. -1.  0.]] 
 et le vecteur de translation [0. 0. 0.] 


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [19]:
## Symétrie 3 : rotation autour d'un axe d'ordre 2 (z, x, -x-y-z)

In [20]:
print("  Nous pouvons voir dans la figure ci dessous que l'atome de Potassium n°2 initialement \n situé aux coordonnées : {0} subit une symétrie de plan miroir pour \n arriver à la position {1}. \n L'opération de symétrie est donnée par la matrice de rotation : \n {2} \n et le vecteur de translation {3} ".format(pos_init_K2, K2_symmetry, s3.rotation_matrix, s3.translation_vector))
v3 = quick_view(conv_struc, conventional = "True")
display(v3)
v3.script("draw SYMOP 15 {atomno=9}")
v3.script("rotate on")

  Nous pouvons voir dans la figure ci dessous que l'atome de Potassium n°2 initialement 
 situé aux coordonnées : [0.75 0.75 0.25] subit une symétrie de plan miroir pour 
 arriver à la position [ 0.25  0.75 -1.75]. 
 L'opération de symétrie est donnée par la matrice de rotation : 
 [[ 0.  0.  1.]
 [ 1.  0.  0.]
 [-1. -1. -1.]] 
 et le vecteur de translation [0. 0. 0.] 


JsmolView(layout=Layout(align_self='stretch', height='400px'))